site_name: Vigilant
repo_name: VerifiedJoseph/vigilant
repo_url: https://github.com/VerifiedJoseph/vigilant
theme:
  name: material
  palette:
    scheme: slate
    primary: black
  font: false
  logo: img/icon.png
  favicon: img/favicon.ico
  icon:
    repo: fontawesome/brands/github

use_directory_urls: false

plugins:
  - privacy
  - offline

nav:
  - "Installation": install.md
  - "Configuration":
      - "Environment variables": configuration.md
      - "Feeds File": feeds.md
  - "Changelog": changelog.md
  - "Development": development.md
  - "Licenses": licenses.md


markdown_extensions:
  - pymdownx.snippets
