site_name: Vigilant
theme:
  name: material
  palette:
    scheme: slate
    primary: black
  font: false
  logo: img/logo/icon.png
  favicon: img/logo/favicon.ico

use_directory_urls: false

plugins:
  - privacy
  - offline

nav:
  - "Home": index.md
  - "Installation": install.md
  - "Configuration":
      - "Environment Variables": environment-variables.md
      - "Feeds File": feeds.md
  - "Changelog": changelog.md
  - "Dev Containers": dev-containers.md
  - "Source Code": "https://github.com/VerifiedJoseph/vigilant"
  - "Licenses": licenses.md

markdown_extensions:
  - pymdownx.snippets
