site_name: Vigilant
repo_name: VerifiedJoseph/vigilant
repo_url: https://github.com/VerifiedJoseph/vigilant
theme:
  name: material
  palette:
    scheme: slate
    primary: black
  logo: assets/logo.png
  favicon: assets/logo.png
  font: false
  logo: img/icon.png
  favicon: img/favicon.ico

use_directory_urls: false

plugins:
  - privacy
  - offline

nav:
  - "Installation": install.md
  - "Configuration":
      - "Environment variables": configuration.md
      - "Feeds File": feeds.md
  - "Changelog": changelog.md
  - "Development": development.md
  - "License": license.md

markdown_extensions:
  - pymdownx.snippets
